version: '3.8'

services:
  web:
    build: ./web
    container_name: web
    volumes:
      - ./web:/app
    ports:
      - "5000:5000"
    command: gunicorn app:app --bind 0.0.0.0:5000 --reload
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - api
      - db
      - redis

  api:
    build: ./api
    container_name: api
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db

  db:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  # worker:
  #   build: ./api
  #   command: celery -A worker.celery worker --loglevel=info --logfile=logs/celery.log
  #   volumes:
  #     - ./api:/app
  #   environment:
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #     - CELERY_RESULT_BACKEND=redis://redis:6379/0
  #   depends_on:
  #     - web
  #     - api
  #     - redis
  #     - db

  # dashboard:
  #   build: ./api
  #   command: celery --broker=redis://redis:6379/0 flower --port=5555
  #   ports:
  #     - 5556:5555
  #   environment:
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #     - CELERY_RESULT_BACKEND=redis://redis:6379/0
  #   depends_on:
  #     - web
  #     - api
  #     - db
  #     - redis
  #     - worker

  redis:
    image: redis:5.0.7-alpine
    ports:
      - "6379:6379"
