version: '3.8'

services:
  web:
    build: ./web
    container_name: web
    volumes:
      - ./web:/app
    ports:
      - "5000:5000"
    command: gunicorn app:app --bind 0.0.0.0:5000 --reload
    env_file:
      - .env
    depends_on:
      - api
      - db
      - redis

  api:
    build: ./api
    container_name: api
    volumes:
      - ./api:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db

  db:
    image: postgres:12.1-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"

  worker:
    build: ./api
    container_name: worker
    volumes:
      - ./api:/app
    env_file:
      - .env
    command: celery -A celery_task_app.worker worker --loglevel=info --logfile=celery.log --concurrency=1
    depends_on:
      - web
      - api
      - redis
      - db

  dashboard:
    build: ./api
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - 5556:5555
    env_file:
      - .env
    depends_on:
      - web
      - api
      - db
      - redis
      - worker

  redis:
    image: redis:7
